# Load Packages

In [1]:
import numpy as np
import pandas as pd

# Import Data

In [2]:
F2Fmerged_raw = pd.read_csv("Eternals' Group Project - f2fMerged_raw.csv")

# View Data

In [3]:
F2Fmerged_raw.head()

UID   Section  Group  Sum_Introversion  Sum_Extraversion  \
0  10267.0  F2F_2021   24.0              24.0              11.0   
1  23143.0  F2F_2021    8.0              20.0              13.0   
2  23144.0  F2F_2021    8.0               NaN               NaN   
3  23145.0  F2F_2021    5.0              18.0              18.0   
4  23146.0  F2F_2021   21.0              26.0               8.0   

   TBL1_iRAT (Module 1: iRAT -- Requires Respondus LockDown Browser (5 points))  \
0                                                3.0                              
1                                                3.0                              
2                                                4.0                              
3                                                4.0                              
4                                                4.0                              

   TBL2_iRAT (Module 2: iRAT - Requires Respondus LockDown Browser + Webcam (5 points))  \
0                                                2.0                                      
1                                                2.0                                      
2                                                2.0                                      
3                                                2.0                                      
4                                                2.0                                      

   TBL3_iRAT (Module 3: iRAT - Requires Respondus LockDown Browser + Webcam (5 points))  \
0                                                5.0                                      
1                                                3.0                                      
2                                                3.0                                      
3                                                2.0                                      
4                                                2.0                                      

   TBL1_tRAT (Module 1: tRAT -- Only one Team Member submits (15 points))  \
0                                               15.0                        
1                                               15.0                        
2                                               15.0                        
3                                               15.0                        
4                                               15.0                        

   TBL2_tRAT (Module 2: tRAT -- Only one Team Member submits (15 points))  \
0                                               14.0                        
1                                               14.0                        
2                                               14.0                        
3                                               15.0                        
4                                               12.0                        

   TBL3_tRAT (Module 3: tRAT -- Only one Team Member submits (15 points))  
0                                               15.0                       
1                                               15.0                       
2                                               15.0                       
3                                               14.0                       
4                                               15.0

In [4]:
F2Fmerged_raw.info

<bound method DataFrame.info of          UID   Section  Group  Sum_Introversion  Sum_Extraversion  \
0    10267.0  F2F_2021   24.0              24.0              11.0   
1    23143.0  F2F_2021    8.0              20.0              13.0   
2    23144.0  F2F_2021    8.0               NaN               NaN   
3    23145.0  F2F_2021    5.0              18.0              18.0   
4    23146.0  F2F_2021   21.0              26.0               8.0   
..       ...       ...    ...               ...               ...   
619  19143.0  F2F_2019    3.0              29.0               5.0   
620  19144.0  F2F_2019    8.0              18.0              17.0   
621  19145.0  F2F_2019   10.0              29.0               6.0   
622  19153.0  F2F_2019   15.0              15.0              18.0   
623      NaN       NaN    NaN               NaN               NaN   

     TBL1_iRAT (Module 1: iRAT -- Requires Respondus LockDown Browser (5 points))  \
0                                                  3.0

# Check the Shape of the Dataframe

In [5]:
F2Fmerged_raw.shape

(624, 11)

# Descriptive Stats

In [7]:
F2Fmerged_raw.describe().transpose()

count          mean  \
UID                                                 623.0  20866.882825   
Group                                               618.0     13.236246   
Sum_Introversion                                    617.0     17.270665   
Sum_Extraversion                                    617.0     17.505673   
TBL1_iRAT (Module 1: iRAT -- Requires Respondus...  622.0      3.495177   
TBL2_iRAT (Module 2: iRAT - Requires Respondus ...  623.0      2.717496   
TBL3_iRAT (Module 3: iRAT - Requires Respondus ...  622.0      2.922830   
TBL1_tRAT (Module 1: tRAT -- Only one Team Memb...  623.0     14.691814   
TBL2_tRAT (Module 2: tRAT -- Only one Team Memb...  623.0     13.452648   
TBL3_tRAT (Module 3: tRAT -- Only one Team Memb...  621.0     14.181965   

                                                            std      min  \
UID                                                 1810.036715  10267.0   
Group                                                  7.381205      1.0   
Sum_Introversion                                       6.335045      2.0   
Sum_Extraversion                                       6.517986      2.0   
TBL1_iRAT (Module 1: iRAT -- Requires Respondus...     1.080858      0.0   
TBL2_iRAT (Module 2: iRAT - Requires Respondus ...     1.087993      0.0   
TBL3_iRAT (Module 3: iRAT - Requires Respondus ...     1.210725      0.0   
TBL1_tRAT (Module 1: tRAT -- Only one Team Memb...     1.141745      0.0   
TBL2_tRAT (Module 2: tRAT -- Only one Team Memb...     1.702256      0.0   
TBL3_tRAT (Module 3: tRAT -- Only one Team Memb...     1.350291      0.0   

                                                        25%      50%      75%  \
UID                                                 18998.5  21081.0  23155.5   
Group                                                   7.0     13.0     20.0   
Sum_Introversion                                       13.0     18.0     22.0   
Sum_Extraversion                                       13.0     17.0     22.0   
TBL1_iRAT (Module 1: iRAT -- Requires Respondus...      3.0      4.0      4.0   
TBL2_iRAT (Module 2: iRAT - Requires Respondus ...      2.0      3.0      3.0   
TBL3_iRAT (Module 3: iRAT - Requires Respondus ...      2.0      3.0      4.0   
TBL1_tRAT (Module 1: tRAT -- Only one Team Memb...     15.0     15.0     15.0   
TBL2_tRAT (Module 2: tRAT -- Only one Team Memb...     13.0     14.0     15.0   
TBL3_tRAT (Module 3: tRAT -- Only one Team Memb...     14.0     15.0     15.0   

                                                        max  
UID                                                 23728.0  
Group                                                  26.0  
Sum_Introversion                                       33.0  
Sum_Extraversion                                       34.0  
TBL1_iRAT (Module 1: iRAT -- Requires Respondus...      5.0  
TBL2_iRAT (Module 2: iRAT - Requires Respondus ...      5.0  
TBL3_iRAT (Module 3: iRAT - Requires Respondus ...      5.0  
TBL1_tRAT (Module 1: tRAT -- Only one Team Memb...     15.0  
TBL2_tRAT (Module 2: tRAT -- Only one Team Memb...     15.0  
TBL3_tRAT (Module 3: tRAT -- Only one Team Memb...     16.0

# Renaming Columns For TBLs 1-3

In [15]:
F2Fmerged_raw.rename(columns = {'TBL1_iRAT (Module 1: iRAT -- Requires Respondus LockDown Browser (5 points))':'TBL1_iRAT', 'TBL2_iRAT (Module 2: iRAT - Requires Respondus LockDown Browser + Webcam (5 points))':'TBL2_iRAT','TBL3_iRAT (Module 3: iRAT - Requires Respondus LockDown Browser + Webcam (5 points))':'TBL3_iRAT', 'TBL1_tRAT (Module 1: tRAT -- Only one Team Member submits (15 points))':'TBL1_tRAT','TBL2_tRAT (Module 2: tRAT -- Only one Team Member submits (15 points))':'TBL2_tRAT', 'TBL3_tRAT (Module 3: tRAT -- Only one Team Member submits (15 points))':'TBL3_tRAT'}, inplace = True)

# Viewing Updated Rename Columns

In [19]:
F2Fmerged_raw

UID   Section  Group  Sum_Introversion  Sum_Extraversion  TBL1_iRAT  \
0    10267.0  F2F_2021   24.0              24.0              11.0        3.0   
1    23143.0  F2F_2021    8.0              20.0              13.0        3.0   
2    23144.0  F2F_2021    8.0               NaN               NaN        4.0   
3    23145.0  F2F_2021    5.0              18.0              18.0        4.0   
4    23146.0  F2F_2021   21.0              26.0               8.0        4.0   
..       ...       ...    ...               ...               ...        ...   
619  19143.0  F2F_2019    3.0              29.0               5.0        3.0   
620  19144.0  F2F_2019    8.0              18.0              17.0        4.0   
621  19145.0  F2F_2019   10.0              29.0               6.0        4.0   
622  19153.0  F2F_2019   15.0              15.0              18.0        5.0   
623      NaN       NaN    NaN               NaN               NaN        5.0   

     TBL2_iRAT  TBL3_iRAT  TBL1_tRAT  TBL2_tRAT  TBL3_tRAT  
0          2.0        5.0       15.0       14.0       15.0  
1          2.0        3.0       15.0       14.0       15.0  
2          2.0        3.0       15.0       14.0       15.0  
3          2.0        2.0       15.0       15.0       14.0  
4          2.0        2.0       15.0       12.0       15.0  
..         ...        ...        ...        ...        ...  
619        4.0        5.0       15.0       14.0       15.0  
620        4.0        4.0       15.0       14.0       14.0  
621        4.0        4.0       14.0       15.0       13.0  
622        4.0        4.0       15.0       14.0       15.0  
623        5.0        5.0       15.0       15.0       15.0  

[624 rows x 11 columns]

# Viewing Arrays in Section, Group and TBLs 1-3

In [20]:
F2Fmerged_raw.Section.unique()

array(['F2F_2021', 'F2F_2020', 'F2F_2019', nan], dtype=object)

In [21]:
F2Fmerged_raw.Group.unique()

array([24.,  8.,  5., 21.,  9., 11., 14., 22., 13., 20.,  1., 16., 25.,
        6., 12.,  7.,  3., 19., 18., 23.,  4., 10., 17., 15.,  2., nan,
       26.])

In [22]:
F2Fmerged_raw.TBL1_iRAT.unique()

array([ 3.,  4.,  5.,  2.,  1.,  0., nan])

In [23]:
F2Fmerged_raw.TBL2_iRAT.unique()

array([ 2.,  3.,  0.,  4.,  1., nan,  5.])

In [24]:
F2Fmerged_raw.TBL3_iRAT.unique()

array([ 5.,  3.,  2.,  4.,  1.,  0., nan])

In [25]:
F2Fmerged_raw.TBL1_tRAT.unique()

array([15., 12.,  0., 14., nan])

In [26]:
F2Fmerged_raw.TBL2_tRAT.unique()

array([14., 15., 12., 13., 11.,  8., nan,  0., 10.])

In [27]:
F2Fmerged_raw.TBL3_tRAT.unique()

array([15., 14., 12., 13., nan,  0., 10., 16.])